# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jdplus.main.ws.v1 import toolkit_messages_pb2 as jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jdplus/main/ws/v1/toolkit_basic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TsFunctionsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/GetVersion',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.EmptyDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.VersionInfoDto.FromString,
                _registered_method=True)
        self.Normalize = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/Normalize',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.NormalizeStream = channel.stream_stream(
                '/jdplus.main.ws.v1.TsFunctions/NormalizeStream',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.Statistics = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/Statistics',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DescriptiveStatisticsDto.FromString,
                _registered_method=True)
        self.StatisticsStream = channel.stream_stream(
                '/jdplus.main.ws.v1.TsFunctions/StatisticsStream',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DescriptiveStatisticsDto.FromString,
                _registered_method=True)
        self.Pct = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/Pct',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.PctInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.PctStream = channel.stream_stream(
                '/jdplus.main.ws.v1.TsFunctions/PctStream',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.PctInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.Delta = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/Delta',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DeltaInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.DeltaStream = channel.stream_stream(
                '/jdplus.main.ws.v1.TsFunctions/DeltaStream',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DeltaInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.Aggregate = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/Aggregate',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.AggregationInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.AggregateStream = channel.stream_stream(
                '/jdplus.main.ws.v1.TsFunctions/AggregateStream',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.AggregationInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.HodrickPrescott = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/HodrickPrescott',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottOutputDto.FromString,
                _registered_method=True)
        self.HodrickPrescottStream = channel.stream_stream(
                '/jdplus.main.ws.v1.TsFunctions/HodrickPrescottStream',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottOutputDto.FromString,
                _registered_method=True)
        self.BuildTsData = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/BuildTsData',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.BuildTsDataStream = channel.stream_stream(
                '/jdplus.main.ws.v1.TsFunctions/BuildTsDataStream',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
                _registered_method=True)
        self.BuildTsDataTable = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/BuildTsDataTable',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataTableInputDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataTableOutputDto.FromString,
                _registered_method=True)
        self.ProcessTemporalDisaggregation = channel.unary_unary(
                '/jdplus.main.ws.v1.TsFunctions/ProcessTemporalDisaggregation',
                request_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TemporalDisaggregationRequestDto.SerializeToString,
                response_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TemporalDisaggregationResultsDto.FromString,
                _registered_method=True)


class TsFunctionsServicer:
    """Missing associated documentation comment in .proto file."""

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Normalize(self, request, context):
        """Compute (y-mean(y))/stdev(y) 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NormalizeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Statistics(self, request, context):
        """Basic descriptive statistics 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatisticsStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PctStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeltaStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Aggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HodrickPrescott(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HodrickPrescottStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildTsData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildTsDataStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildTsDataTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessTemporalDisaggregation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TsFunctionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.EmptyDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.VersionInfoDto.SerializeToString,
            ),
            'Normalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Normalize,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'NormalizeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.NormalizeStream,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'Statistics': grpc.unary_unary_rpc_method_handler(
                    servicer.Statistics,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DescriptiveStatisticsDto.SerializeToString,
            ),
            'StatisticsStream': grpc.stream_stream_rpc_method_handler(
                    servicer.StatisticsStream,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DescriptiveStatisticsDto.SerializeToString,
            ),
            'Pct': grpc.unary_unary_rpc_method_handler(
                    servicer.Pct,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.PctInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'PctStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PctStream,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.PctInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'Delta': grpc.unary_unary_rpc_method_handler(
                    servicer.Delta,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DeltaInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'DeltaStream': grpc.stream_stream_rpc_method_handler(
                    servicer.DeltaStream,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DeltaInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'Aggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.Aggregate,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.AggregationInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'AggregateStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AggregateStream,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.AggregationInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'HodrickPrescott': grpc.unary_unary_rpc_method_handler(
                    servicer.HodrickPrescott,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottOutputDto.SerializeToString,
            ),
            'HodrickPrescottStream': grpc.stream_stream_rpc_method_handler(
                    servicer.HodrickPrescottStream,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottOutputDto.SerializeToString,
            ),
            'BuildTsData': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildTsData,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'BuildTsDataStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BuildTsDataStream,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.SerializeToString,
            ),
            'BuildTsDataTable': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildTsDataTable,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataTableInputDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataTableOutputDto.SerializeToString,
            ),
            'ProcessTemporalDisaggregation': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTemporalDisaggregation,
                    request_deserializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TemporalDisaggregationRequestDto.FromString,
                    response_serializer=jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TemporalDisaggregationResultsDto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jdplus.main.ws.v1.TsFunctions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jdplus.main.ws.v1.TsFunctions', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TsFunctions:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/GetVersion',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.EmptyDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.VersionInfoDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Normalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/Normalize',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NormalizeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jdplus.main.ws.v1.TsFunctions/NormalizeStream',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Statistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/Statistics',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DescriptiveStatisticsDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatisticsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jdplus.main.ws.v1.TsFunctions/StatisticsStream',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DescriptiveStatisticsDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/Pct',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.PctInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PctStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jdplus.main.ws.v1.TsFunctions/PctStream',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.PctInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/Delta',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DeltaInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeltaStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jdplus.main.ws.v1.TsFunctions/DeltaStream',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.DeltaInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Aggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/Aggregate',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.AggregationInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggregateStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jdplus.main.ws.v1.TsFunctions/AggregateStream',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.AggregationInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HodrickPrescott(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/HodrickPrescott',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HodrickPrescottStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jdplus.main.ws.v1.TsFunctions/HodrickPrescottStream',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.HodrickPrescottOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildTsData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/BuildTsData',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildTsDataStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jdplus.main.ws.v1.TsFunctions/BuildTsDataStream',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TsFunctionOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildTsDataTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/BuildTsDataTable',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataTableInputDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.BuildTsDataTableOutputDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessTemporalDisaggregation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jdplus.main.ws.v1.TsFunctions/ProcessTemporalDisaggregation',
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TemporalDisaggregationRequestDto.SerializeToString,
            jdplus_dot_main_dot_ws_dot_v1_dot_toolkit__messages__pb2.TemporalDisaggregationResultsDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
